### ISSUE TITLE
Detection fails on particular, simple ANSI file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [UniversalCharsetDetector/ude#7] opened 2015-03-19 23:39 UTC
```
What steps will reproduce the problem?
1. Save an ANSI file containing the text "CONFIG: main 30000000"
2. Run the library and/or exe on it

What is the expected output? What do you see instead?

I expect ANSI detected.

What version of the product are you using? On what operating system?

The library shows null for charset, and the exe shows "detection failed".

Please provide any additional information below.

I don't know if this is how the library is intended to work, but I think it 
would be more useful to detect ANSI if all the characters fit into ANSI. Or at 
least support this behavior optionally.
```

Original issue reported on code.google.com by `john.bu...@gmail.com` on 14 Sep 2014 at 4:59

**Comment by 304NotModified** [comment] 2015-11-25 23:39
duplicate of https://github.com/UniversalCharsetDetector/ude/issues/3 and has been fixed already

**Closed by 304NotModified** 2015-11-25 23:39 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect

**Comment by 304NotModified** [comment] 2017-04-07 21:23
See https://github.com/errepi/ude/issues/7
